Fix SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR requires SDK >= 26
immuni-app/immuni-app-android pull request #17
Opened 2020-05-25 11:02 UTC by Datalux

## Description
In files **BottomSheetDialogDarkFragment.kt** (line 29) and **BottomSheetDialogLightFragment** (line 87) there is a check for SDK >= 23 (the minSdkVersion is already 23) and   `SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR` requires SDK >= 26.

This PR tackles:

- changed the checked SDK version to 26

## Checklist

- [X] I have followed the indications in the [CONTRIBUTING](../CONTRIBUTING.md).
- [ ] The documentation related to the proposed change has been updated accordingly (plus comments in code).
- [ ] I have written new tests for my core changes, as applicable.
- [X] I have successfully run tests with my changes locally.
- [ ] It is ready for review! :rocket:

## Fixes

- Fixes #16

2020-05-25 11:15 UTC, ImmuniDGR commented
🚔 **Safety Check** 🚔

🔰 **Result** 🔰


✅ All configuration files are in line with the master branch.

🛠 **Diagnostic information** 🛠
- CircleCI scheduler pipeline: #64 (id: 13ae085a-ca75-47e0-8ea3-564e11e29e14)
- Last verified commit: #b776f5c5c4716e5ba4ec04c22a2160150813803a
- Time of check: 25/05/2020, 11:15:54 UTC
- The following protected files have been checked for changes: template.properties, .editorconfig, yarn.lock, app/build.gradle, Gemfile.lock, Gemfile, ci/danger/commitlint/rules.ts, gradlew, scheduler_config.json, gradlew.bat, dangerfile.ts, ci/danger/danger.ts, app/proguard-rules.pro, fastlane/Appfile, settings.gradle, ci/danger/ktlint.ts, ci/changelog_config.tpl, ci/danger/commitlint/index.ts, .gitmodules, build.gradle, gradle.properties, publiccode.yml, fastlane/Fastfile, package.json.

2020-05-25 11:39 UTC, marcouberti submitted a review, later dismissed

2020-05-25 13:17 UTC, marcouberti commented on app/src/main/java/it/ministerodellasalute/immuni/ui/dialog/BottomSheetDialogLightFragment.kt
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR should be set for API M+ too. So probably it is needed some additional if block.

2020-05-25 13:18 UTC, marcouberti requested changes
The changes don't consider the View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR flag to be used in Android M+ devices.

2020-05-25 13:31 UTC, ImmuniDGR commented
🚔 **Safety Check** 🚔

🔰 **Result** 🔰


✅ All configuration files are in line with the master branch.

🛠 **Diagnostic information** 🛠
- CircleCI scheduler pipeline: #76 (id: 45daea04-204d-4974-9ed1-4c3f4b776dd9)
- Last verified commit: #ccc32aebaaf50d5f7377f7a7a77f6bd883daa2d2
- Time of check: 25/05/2020, 13:31:13 UTC
- The following protected files have been checked for changes: ci/danger/ktlint.ts, app/proguard-rules.pro, gradlew.bat, publiccode.yml, .gitmodules, package.json, gradle.properties, gradlew, ci/danger/danger.ts, ci/danger/commitlint/rules.ts, template.properties, fastlane/Fastfile, dangerfile.ts, fastlane/Appfile, Gemfile.lock, settings.gradle, yarn.lock, ci/danger/commitlint/index.ts, ci/changelog_config.tpl, scheduler_config.json, app/build.gradle, Gemfile, build.gradle, .editorconfig.

2020-05-25 13:39 UTC, Datalux commented
@madbat my bad, I fixed this.
Now it check both for M and O SDK and add SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR only for SDK >= O

2020-05-25 19:29 UTC, Datalux reviewed
Check for M and O SDK

2020-07-21 12:47 UTC, marcouberti approved these changes

2022-01-06 17:27 UTC, closed without merging