Cambia gli inglesismi "persona COVID-19 positivo"
immuni-app/immuni-app-android pull request #265
Opened 2020-08-31 07:13 UTC by rasky

All'interno della app, viene usata più volte la locuzione "persona / utente COVID-19 positiva" che non mi sembra corretto in lingua italiana. Si tratta probabilmente di un inglesismo. 

In questa PR, ho modificato tutte le occorrenza uniformando il riferimento da "utente" a "persona", e cambiando la locuzione in "persona positiva/negativa al COVID-19".

**NOTA**: Non ho testato questa modifica perché non sono uno sviluppatore Android. È una semplice modifica ai testi che non ne modifica in modo importante la lunghezza, quindi non mi aspetto problemi, ma voi saprete testarla sicuramente in modo opportuno.

2020-08-31 07:25 UTC, ImmuniDGR commented
🚔 **Safety Check** 🚔

🔰 **Result** 🔰
- The following files have been modified: build.gradle.


⚠️ Some configuration files don't match the master branch. If you did not perform these changes, **please rebase on the master branch**.

🛠 **Diagnostic information** 🛠
- CircleCI scheduler pipeline: #9769 (id: 904a1b4e-78ab-448d-8176-97211909edd9)
- Last verified commit: 6f360ab0d51b847bdaf47a93b9b627eaacd1c37f
- Time of check: 31/08/2020, 07:25:46 UTC
- The following protected files have been checked for changes: .editorconfig, .gitmodules, Gemfile, Gemfile.lock, app/build.gradle, app/proguard-rules.pro, build.gradle, ci/changelog\_config.tpl, ci/danger/commitlint/index.ts, ci/danger/commitlint/rules.ts, ci/danger/danger.ts, ci/danger/ktlint.ts, dangerfile.ts, fastlane/Appfile, fastlane/Fastfile, gradle.properties, gradlew, gradlew.bat, package.json, publiccode.yml, scheduler\_config.json, settings.gradle, template.properties, yarn.lock.

2020-11-19 13:33 UTC, ilovelinux commented on app/src/main/res/values-it/strings.xml
> +  <string name="suggestions_risk_subtitle">Immuni ha rilevato che il giorno %@ sei stato vicino ad una persona positiva al COVID-19.</string>
Si scrive "a una" non "ad una", per il resto per me è ok

2020-11-19 13:54 UTC, ilovelinux requested changes

2020-11-19 13:54 UTC, ilovelinux commented on app/src/main/res/values-it/strings.xml
> +  <string name="suggestions_risk_subtitle">Immuni ha rilevato che il giorno %@ sei stato vicino ad una persona positiva al COVID-19.</string>
Si scrive "a una" non "ad una"
```suggestion
  <string name="suggestions_risk_subtitle">Immuni ha rilevato che il giorno %@ sei stato vicino a una persona positiva al COVID-19.</string>
```

2022-01-05 11:16 UTC, merged